// scripts/attribution-lint.test.mjs — the check refuses what it must, and nothing it must not.
// Run with `node --test scripts/`. Drives the CLI through --stdin, which is exactly what CI runs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const SCRIPT = fileURLToPath(new URL("./attribution-lint.mjs", import.meta.url));

function lint(text) {
  const r = spawnSync(process.execPath, [SCRIPT, "--stdin"], { input: text, encoding: "utf8" });
  return { code: r.status, out: r.stdout };
}

const REFUSED = [
  ["an AI co-author trailer", "fix: pin\n\nCo-Authored-By: Claude Opus 5 <noreply@example.com>"],
  ["an AI attribution address", "Co-authored-by: Someone <noreply@anthropic.com>"],
  ["an AI session trailer", "Claude-Session: https://example.com/s"],
  ["a link to an AI coding session", "see https://claude.ai/code/session_abc"],
  ["a generated-with footer", "Generated with [Claude Code](https://example.com)"],
  ["a generated-by-AI footer", "Generated by AI"],
  ["the robot emoji", "\u{1F916} done"],
  ["prose crediting a tool", "This workflow was drafted and refined with Claude."],
  ["prose crediting another tool", "Docs written using ChatGPT."],
  ["a pointer to the private app repo", "see cupel-sh/app for details"],
  ["a pointer to the private engine repo", "the engine lives in cupel-sh/cupel"],
  ["a pointer to the private shard repo", "built by cupel-sh/shard-build"],
  ["a private package path", "the parser in packages/api/src/ingest.ts"],
  ["an internal decision record", "as ADR-063 requires"],
  ["an internal docs path", "see docs/decisions/ADR-001.md"],
  ["agent configuration", "rules live in .claude/rules"],
  ["agent instructions", "per CLAUDE.md"],
];

const ALLOWED = [
  ["an ordinary human co-author", "Co-authored-by: A Person <person@example.com>"],
  ["this public repository", "uses: cupel-sh/scan-workflow/.github/workflows/scan.yml@v1"],
  ["the published CLI package", "npm install @cupel-sh/cli@0.6.0"],
  ["a command-line invocation, not a credit", "the file is not created by claude -p"],
  ["the word generated about a report", "the report is generated with every scan"],
  ["an ordinary sentence mentioning a build", "built by the CI runner using Node 24"],
];

for (const [name, text] of REFUSED) {
  test(`refuses ${name}`, () => {
    const { code, out } = lint(text);
    assert.equal(code, 1, out);
  });
}

for (const [name, text] of ALLOWED) {
  test(`allows ${name}`, () => {
    const { code, out } = lint(text);
    assert.equal(code, 0, out);
  });
}

test("the repository itself is clean", () => {
  const r = spawnSync(process.execPath, [SCRIPT], { encoding: "utf8" });
  assert.equal(r.status, 0, r.stdout);
});

test("an unresolvable base is a usage error, not a pass", () => {
  const r = spawnSync(process.execPath, [SCRIPT, "--commits", "no-such-ref-at-all"], {
    encoding: "utf8",
  });
  assert.equal(r.status, 2);
});
